server:
  port: 8080
  servlet:
    context-path: /api/v1/backend-java-springboot

spring-doc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
  api:
    title: Sistema de Gestion de Productos
    description: Sistema de Gestion de Productos API
    version: 1.0

spring:
  application:
    name: backend-java-springboot

  datasource:
    url: jdbc:postgresql://localhost:5432/PruebaTecnicaBD
    username: postgres
    password: fcHRH2TPJTPKmbd3
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

request-mapping:
  controller:
    company: companies
    product: products
    order: orders
    customer: customers
    category: categories


log4j:
  configurationFile: log4j2-spring.xml, log4j2-env.xml